# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WechatProto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WechatProto.proto',
  package='WechatProto',
  syntax='proto3',
  serialized_pb=_b('\n\x11WechatProto.proto\x12\x0bWechatProto\"q\n\tWechatMsg\x12%\n\x07\x62\x61seMsg\x18\x01 \x01(\x0b\x32\x14.WechatProto.BaseMsg\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x11\n\ttimeStamp\x18\x04 \x01(\x05\x12\n\n\x02iP\x18\x05 \x01(\t\"\xb5\x01\n\x07\x42\x61seMsg\x12\x0b\n\x03ret\x18\x01 \x01(\x05\x12\x0b\n\x03\x63md\x18\x02 \x01(\x05\x12\x0e\n\x06\x63mdUrl\x18\x03 \x01(\t\x12\x11\n\tshortHost\x18\x04 \x01(\t\x12\x10\n\x08longHost\x18\x05 \x01(\t\x12\x1f\n\x04user\x18\x06 \x01(\x0b\x32\x11.WechatProto.User\x12\x10\n\x08longHead\x18\x07 \x01(\x0c\x12\x10\n\x08payloads\x18\x08 \x01(\x0c\x12\x16\n\x0eplayloadextend\x18\t \x01(\x0c\"\xe7\x01\n\x04User\x12\x0b\n\x03uin\x18\x01 \x01(\x03\x12\x0f\n\x07\x63ookies\x18\x02 \x01(\x0c\x12\x12\n\nsessionKey\x18\x03 \x01(\x0c\x12\x10\n\x08\x64\x65viceId\x18\x04 \x01(\t\x12\x12\n\ndeviceType\x18\x05 \x01(\t\x12\x12\n\ndeviceName\x18\x06 \x01(\t\x12\x16\n\x0e\x63urrentsyncKey\x18\x07 \x01(\x0c\x12\x12\n\nmaxSyncKey\x18\x08 \x01(\x0c\x12\x13\n\x0b\x61utoAuthKey\x18\t \x01(\x0c\x12\x0f\n\x07userame\x18\n \x01(\t\x12\x10\n\x08nickname\x18\x0b \x01(\x0c\x12\x0f\n\x07userExt\x18\x0c \x01(\x0c\x32I\n\x06Wechat\x12?\n\x0bHelloWechat\x12\x16.WechatProto.WechatMsg\x1a\x16.WechatProto.WechatMsg\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WECHATMSG = _descriptor.Descriptor(
  name='WechatMsg',
  full_name='WechatProto.WechatMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='baseMsg', full_name='WechatProto.WechatMsg.baseMsg', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='WechatProto.WechatMsg.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='WechatProto.WechatMsg.version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='WechatProto.WechatMsg.timeStamp', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iP', full_name='WechatProto.WechatMsg.iP', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=147,
)


_BASEMSG = _descriptor.Descriptor(
  name='BaseMsg',
  full_name='WechatProto.BaseMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='WechatProto.BaseMsg.ret', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cmd', full_name='WechatProto.BaseMsg.cmd', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cmdUrl', full_name='WechatProto.BaseMsg.cmdUrl', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shortHost', full_name='WechatProto.BaseMsg.shortHost', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longHost', full_name='WechatProto.BaseMsg.longHost', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user', full_name='WechatProto.BaseMsg.user', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longHead', full_name='WechatProto.BaseMsg.longHead', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payloads', full_name='WechatProto.BaseMsg.payloads', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='playloadextend', full_name='WechatProto.BaseMsg.playloadextend', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=331,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='WechatProto.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uin', full_name='WechatProto.User.uin', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cookies', full_name='WechatProto.User.cookies', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sessionKey', full_name='WechatProto.User.sessionKey', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deviceId', full_name='WechatProto.User.deviceId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deviceType', full_name='WechatProto.User.deviceType', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deviceName', full_name='WechatProto.User.deviceName', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currentsyncKey', full_name='WechatProto.User.currentsyncKey', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxSyncKey', full_name='WechatProto.User.maxSyncKey', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='autoAuthKey', full_name='WechatProto.User.autoAuthKey', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userame', full_name='WechatProto.User.userame', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nickname', full_name='WechatProto.User.nickname', index=10,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userExt', full_name='WechatProto.User.userExt', index=11,
      number=12, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=565,
)

_WECHATMSG.fields_by_name['baseMsg'].message_type = _BASEMSG
_BASEMSG.fields_by_name['user'].message_type = _USER
DESCRIPTOR.message_types_by_name['WechatMsg'] = _WECHATMSG
DESCRIPTOR.message_types_by_name['BaseMsg'] = _BASEMSG
DESCRIPTOR.message_types_by_name['User'] = _USER

WechatMsg = _reflection.GeneratedProtocolMessageType('WechatMsg', (_message.Message,), dict(
  DESCRIPTOR = _WECHATMSG,
  __module__ = 'WechatProto_pb2'
  # @@protoc_insertion_point(class_scope:WechatProto.WechatMsg)
  ))
_sym_db.RegisterMessage(WechatMsg)

BaseMsg = _reflection.GeneratedProtocolMessageType('BaseMsg', (_message.Message,), dict(
  DESCRIPTOR = _BASEMSG,
  __module__ = 'WechatProto_pb2'
  # @@protoc_insertion_point(class_scope:WechatProto.BaseMsg)
  ))
_sym_db.RegisterMessage(BaseMsg)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'WechatProto_pb2'
  # @@protoc_insertion_point(class_scope:WechatProto.User)
  ))
_sym_db.RegisterMessage(User)


# @@protoc_insertion_point(module_scope)
