# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!

import WechatProto_pb2 as WechatProto__pb2
import grpc

class WechatStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.HelloWechat = channel.unary_unary(
        '/WechatProto.Wechat/HelloWechat',
        request_serializer=WechatProto__pb2.WechatMsg.SerializeToString,
        response_deserializer=WechatProto__pb2.WechatMsg.FromString,
        )


class WechatServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def HelloWechat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WechatServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'HelloWechat': grpc.unary_unary_rpc_method_handler(
          servicer.HelloWechat,
          request_deserializer=WechatProto__pb2.WechatMsg.FromString,
          response_serializer=WechatProto__pb2.WechatMsg.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'WechatProto.Wechat', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
